# Use the specific Node.js version
FROM node:20
# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your application's source code
COPY . .

# Expose the port your app runs on
EXPOSE 80

# Define the command to run your app
CMD [ "npm", "start" ]